In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data_cleaning sample.csv")

In [3]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [4]:
df1=df.fillna(0)

In [5]:
df['Age'].sum()

np.float64(155.0)

In [6]:
df['Age'].mean()

np.float64(25.833333333333332)

In [7]:
df['Age'].std()

2.786873995477131

In [8]:
df['Age'].min()

22.0

In [9]:
df['Age'].max()

30.0

In [10]:
df['Age'].count()

np.int64(6)

In [11]:
df.describe()

             Age
count   6.000000
mean   25.833333
std     2.786874
min    22.000000
25%    25.000000
50%    25.000000
75%    27.250000
max    30.000000